### ISSUE TITLE
Speicherung der jedes Codes in einem Datenbankfeld

### ISSUE THREAD

**Issue by btosh82** [heimrichhannot/contao-code-generator-bundle#2]
Ist es möglich bei der Generierung der Codes diese auch, statt in einer Textdatei auszugeben, in einer Spalte einer Datenbank zu speichern, jeden Code in einem eigenen Feld?

**Comment by Defcon0** [comment]
Das ist leider noch nicht möglich, wird aber evtl. bald kommen, da evtl. ein entsprechendes Projekt kommt.

**Comment by btosh82** [comment]
OK, danke für die Info. Wahrscheinlich bedeutet "bald evtl" nicht in den nächsten 4–6 Wochen :)

**Comment by Defcon0** [comment]
Der Kunde ist nicht gerade der schnellste, ich würde eher von 2-3 Monaten ausgehen.

**Comment by btosh82** [comment]
Wie schreibe ich Dir ne PM? Was würde die Ergänzung an Aufwand/Kosten bedeuten?

**Comment by Defcon0** [comment]
Hab mal kurz meine Mail-Adresse im Profil aktiviert. Schreib mir eine Mail und wir schauen mal.
